In [1]:

from Competitions import *
#with open('Pickles/TEST_1mar2026.pkl', 'wb') as f:
    #pickle.dump({'Roster': ALLROSTERED, 'handle': GLOBALHANDLER}, f)

pygame 2.6.1 (SDL 2.28.4, Python 3.13.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
London
                        ShooterRating  sweep  DIFF   User  Composite  Help
श्रीमान सुरेश त्रिवेदी          74.40  80.52 -6.11  False      31.09     0
السيد غزير طسم                  97.60  93.50  4.10  False      52.91     0
Giampiero Antonello             89.09  68.48 20.61  False      65.16     1
Aidan Herzig                   104.00 100.00  4.00   True    1056.00     2
United States
                 ShooterRating  sweep  DIFF   User  Composite  Help
Tyler Carpenter          95.11  69.93 25.18  False      72.74     0
Ryan Decker              99.55  75.00 24.55  False      74.32     0
Pedro Rodriguez          95.29  61.21 34.08  False      81.72     1
Aidan Herzig            104.00 100.00  4.00   True    1056.00     2

In [119]:
GLOBALHANDLER.displayNextSlate()

Season Over

In [118]:
GLOBALHANDLER.playNextSlate()

c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv
c:\Users\leojo\OneDrive\Documents\GitHub\AWH_Curling3\Shot.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-2.296212748401287e-19' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  SHEET.df.loc[stoneid, 'xv'] = xv

In [88]:
GLOBALHANDLER.LEAGUES['United Kingdom'].displayNextSlate()

United Kingdom Playoffs
#1 London vs #9 Sheffield

In [86]:
GLOBALHANDLER.LEAGUES['United Kingdom'].BRACKET.pygameDisplay()

error: video system not initialized

In [79]:
GLOBALHANDLER.CL['Europe'].displayNextSlate()

Europe CL Knockouts
#5 London vs #3 Leipzig

In [120]:
GLOBALHANDLER.WCQ['Americas'].RR.STANDINGS

               Wins  Losses  EEWins  PD
United States     8       0       0  38
Canada            5       3       1   7
Colombia          5       3       1  -5
Mexico            4       4       0   2
Argentina         4       4       0   0
Chile             4       4       1  -3
Brazil            3       5       0  -3
Peru              2       6       0 -11
Ecuador           1       7       0 -25

In [282]:
GLOBALHANDLER.CWC.GROUP.STANDINGS

AttributeError: 'NoneType' object has no attribute 'GROUP'

In [121]:
GLOBALHANDLER.WINNERS

     YEAR             COMPETITION         WINNER
0       1    Asia CL Quals Path 1          Xi'an
1       1    Asia CL Quals Path 2           Pune
2       1    Asia CL Quals Path 3         Dalian
3       1    Asia CL Quals Path 4       Brisbane
4       1    Asia CL Quals Path 5        Jakarta
..    ...                     ...            ...
335     2  United States Playoffs         Dallas
336     2        Vietnam Playoffs          Hanoi
337     2         CWC GROUP STAGE         Sydney
338     2               CWC FINAL         Sydney
339     2     WORLD CUP KNOCKOUTS  United States

[340 rows x 3 columns]

In [245]:
GLOBALHANDLER.RESULTS.to_csv('Output/RESULTS.csv')
GLOBALHANDLER.WINNERS.to_csv('Output/WINNERS.csv')

In [250]:
ALLROSTERED = GLOBALHANDLER.reset(ALLROSTERED)

0
London
                        ShooterRating  sweep  DIFF   User  Composite  Help
श्रीमान सुरेश त्रिवेदी          74.40  80.52 -6.11  False      31.09     0
السيد غزير طسم                  97.60  93.50  4.10  False      52.91     0
Giampiero Antonello             89.09  68.48 20.61  False      65.16     1
Aidan Herzig                   104.00 100.00  4.00   True    1056.00     2
United States
                 ShooterRating  sweep  DIFF   User  Composite  Help
Tyler Carpenter          95.11  69.93 25.18  False      72.74     0
Ryan Decker              99.55  75.00 24.55  False      74.32     0
Pedro Rodriguez          95.29  61.21 34.08  False      81.72     1
Aidan Herzig            104.00 100.00  4.00   True    1056.00     2

In [125]:
with open('Pickles/REAL2_8Mar26_3.pkl', 'wb') as f:
    pickle.dump({'Roster': ALLROSTERED, 'handle': GLOBALHANDLER}, f)

In [124]:
import chess